### ISSUE TITLE
Error on launch - Image.ANTIALIAS is Deprecated in later version of PIL

### ISSUE THREAD

**Issue by gerap-mmuk** [theallyprompts/PixelPruner#1]
Howdy!

Common issue I run into all the time with the Pillow library - GPT loves to tell you to use Image.ANTIALIAS, but in updated versions of this library, that feature has been deprecated, so when I run the steps in the readme and launch the app, I get the following:

$ python PixelPruner.py
Traceback (most recent call last):
  File "U:\scripts\PixelPruner-main\PixelPruner.py", line 512, in <module>
    main()
  File "U:\scripts\PixelPruner-main\PixelPruner.py", line 508, in main
    app = PixelPruner(root)
          ^^^^^^^^^^^^^^^^^
  File "U:\scripts\PixelPruner-main\PixelPruner.py", line 166, in __init__
    self.load_image()
  File "U:\scripts\PixelPruner-main\PixelPruner.py", line 223, in load_image
    self.display_image()
  File "U:\scripts\PixelPruner-main\PixelPruner.py", line 230, in display_image
    self.tkimage = ImageTk.PhotoImage(self.current_image.resize((self.scaled_width, self.scaled_height), Image.ANTIALIAS))
                                                                                                         ^^^^^^^^^^^^^^^
AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'

The fix is to replace Image.ANTIALIAS with Image.Resampling.LANCZOS, if you are using Pillow version 10.0.0 or later. If backwards compatilbity is important, the version of the package can be detected and an if statement used to invoke antialias or resampling as appropriate.

**Comment by theallyprompts** [comment]
Thanks, Sir! Fixed in version 1.1, soon to be released! I'm now checking for the Pillow version and picking the best method based on that, per your recommendation. Thanks!

**Comment by elyetis** [comment]
Just did a manual installation, I had to replace `if PILLOW_VERSION >= "7.0.0":` line 280, with `if PILLOW_VERSION >= "10.0.0":` to get past the AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'.
